### ISSUE TITLE
Return of "Error in if (nrow(MissingFromFields) > 0) { : argument is of length zero"

### ISSUE THREAD

**Issue by baderstine** [vubiostat/redcapAPI#413]
I'm running v2.9.1 and getting this error (see: #314): 

``` 
> exportRecordsTyped(rcon) 
Error in if (nrow(MissingFromFields) > 0) { : argument is of length zero

> exportRecords(rcon) 
Please use exportRecordsTyped instead. exportRecords is will undergo breaking changes in version 3.0.0.
Error in MetaData$form_name : $ operator is invalid for atomic vectors
```

What is the workaround?

**Comment by baderstine** [comment]
OK, this is just a case of an unhelpful error message.  The API token I was using was invalid, it had been changed to a new token.  Is that a check you can add and give a more helpful error message?

**Comment by spgarbet** [comment]
Interesting, this should certainly be a better message. Did you use unlockREDCap? It has the checks on the token and should respond appropriately.

I recently refactored the makeAPICall routine and this sounds like a bug that was introduced at that level and even if unlockREDCap wasn't used it should give a better message.

**Comment by spgarbet** [comment]
I'm on version 2.10.0 which is post the refactor. This is what it shows me:

```
> library(redcapAPI)
> 
> rconn <- redcapConnection(token="BAD", url="https://redcap.vumc.org/api/")
> 
> exportRecords(rconn)
Please use exportRecordsTyped instead. exportRecords is will undergo breaking changes in version 3.0.0.
Error in redcapError(response) : 
  403: ERROR: You do not have permissions to use the API
```

**Comment by spgarbet** [comment]
2.10.0 has not been pushed to CRAN. Seems like the fix to this is to push the recent version out as a release.

@jubilee2 @graywh @obregos This is post the major refactor of API calls and gets rid of httr dependencies. Are we using this version yet, i.e. has it been vetted enough to push to CRAN? The tests have been stable for some time.

**Comment by spgarbet** [comment]
The release has been pushed to CRAN that includes this enhancement.

**Comment by baderstine** [comment]
Updated to 2.10.0 - I was getting the same unhelpful error messages as I previously reported for v2.9.1... but this time I know that my token is good.  However, my institution changed their URL for the API endpoint and the one I was using didn't work. 

Any chance you could update the error messages to indicate a bad URL?

**Comment by spgarbet** [comment]
@baderstine Can you give me some detail of what you see with the wrong URL. I expect you would have gotten a 405 error and a message about unable to connect to the URL.

**Comment by spgarbet** [comment]
Ah, interesting. This is different than I thought. 302 is a temporary redirect. It's doing a forward. Think it's pulling the new URL correctly but dropping the rest of the path. We didn't get a chance to test this when our server moved. This is a very tricky bit.

**Comment by spgarbet** [comment]
The fix is merged onto the main branch now. @baderstine if you could test that would be helpful.

**Comment by baderstine** [comment]
Still getting `Error in if (nrow(MissingFromFields) > 0) { : argument is of length zero` when i attempt to run `exportRecordsTyped(con)` using the url that redirects.  What should I expect to see?  Or is there some specific code you'd like me to run?

**Comment by spgarbet** [comment]
`devtools::install_github('vubiostat/redcapAPI')` will install the edge version.

**Comment by baderstine** [comment]
I cloned the repo, built and installed it, so i'm running 2.10.1.  

```r
library(redcapAPI)
con = redcapConnection(url, token, config)
exportRecordsTyped(con)
``` 

Good url, good token: everything works fine.

Good url, bad token: 
`Error in redcapError(response) : 
  403: ERROR: You do not have permissions to use the API` 

Bad url, good token:
`Error in if (nrow(MissingFromFields) > 0) { : argument is of length zero`

**Comment by spgarbet** [comment]
Thanks. 

I'm at a bit of a loss how to proceed. The "bad url" response is basically getting a response and then crashing trying to read it at some point. Would it be possible to create a test project and grant me API access? We should coordinate via email if so, shawn<dot>garbett<at>vumc.org.

**Comment by baderstine** [comment]
All our stuff is behind VPN that I cannot grant access.

**Comment by spgarbet** [comment]
Okay. I think I might be able to set up a local redirect server.

**Comment by spgarbet** [comment]
@baderstine I've setup a local server and worked through getting the redirect to work properly. I never recreated the bug you've been seeing, but I did get a different one and was able to fix the redirect code. 

If you could test this branch, it would be helpful:

`devtools::install_github("vubiostat/redcapAPI", ref="redirect-413")`

**Comment by baderstine** [comment]
Now I get four messages like:
"Temporary 302 redirect <url i passed in> to <multiple incorrect url strings separated by %22>".  

It looks like the redirect is trying to open an SSO authentication prompt rather than just use the token to redirect to the correct url.  So, this is likely a problem with our institution's redirect.  Anyway, very helpful to have the extra redirect message printed out. I'd consider this fixed.

**Comment by spgarbet** [comment]
Well some good came of this, as redirect is working properly now.
