### ISSUE TITLE
exportBundle bug

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#43]
A user reported that exportBundle doesn't work for any project. They said it always fails with 'replacement has zero rows.'

**Comment by spgarbet** [comment]
I just tried this with the current version with the round of bug fixes and it's working for me. Will see if user still has the problem with the latest version.

**Comment by nutterb** [comment]
Wait!  There's someone out there that actually uses the bundle!? I have so many questions!  :)

I would have guessed it was the users. I think that was the error I was getting when trying exportUsers.  I also would expect it works after yesterdays pushes. 

They may also be interested in knowing that the new caching renders the bundle obsolete. Well, almost. Apparently we aren't caching exportInstruments, which is included in the bundle.

**Comment by spgarbet** [comment]
I think this is fixed if it worked with users=FALSE. Leaving this open to continue the discussion.

**Comment by nutterb** [comment]
@omair-a-khan I'm mostly surprised that it's being used. As I finished writing it, I remember thinking to myself that it was probably wasted time, because I wasn't convinced anyone would ever use it. I don't think I've ever used it myself, for that matter. 

I'll admit, I had this in my cross-hairs as something that could be removed from the package. I don't want to do that if it's going to create headaches though. So, help me understand how you use this and what value it brings you.

1. Why did you start using exportBundle?
2. How often do you use it? 
3. What parts of the bundle do you use?
4. How do you use it in your workflow?
5. Is there anything you would add to it that would make it more valuable?
6. If it were to be removed (emphasis on _if_), how catastrophic would it be to your workflow?

**Comment by nutterb** [comment]
To clarify, `exportBundle` still exists as a function. I didn't want to pull it unexpectedly, as it seems @omair-a-khan , at least, is using it. But nothing in the package utilizes it.

**Comment by nutterb** [comment]
Thanks for the feedback. I won't feel bad about cutting this out in some future 3.0 version. :)
